version: "3.7"

networks:
  cmc-net:
    driver: "bridge"

services:
  php-cli:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    volumes:
      - ../:/mnt/app
    networks:
      - cmc-net
    links:
      - cmc-redis

  cmc-redis:
    image: redis:4.0
    container_name: crawler_redis
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "6383:6379"
    networks:
      - cmc-net